steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/estefania-359014/bq-to-ftp', '.' , '-f', 'Dockerfile']
  # push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/estefania-359014/bq-to-ftp']
images:
  - 'gcr.io/estefania-359014/bq-to-ftp'