steps:
- name: 'gcr.io/cloud-builders/npm'
    args: ['install']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--tag=southamerica-east1-docker.pkg.dev/estefania-359014/dockercloud/app-image', '.']
  # push the container image to Container Registry
images:
  - 'southamerica-east1-docker.pkg.dev/estefania-359014/dockercloud/app-image'

